[package]
name = "cc-client"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tarpc.workspace = true
tokio-serde.workspace = true
futures.workspace = true

client.workspace = true
crypto.workspace = true

cfgmatic-paths = "5.0.1"
url = "2.5.8"
service-manager = "0.11.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_SystemServices",
] }
windows-service = "0.7.0"
