[package]
name = "client"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
hyper-util.workspace = true
hyper.workspace = true
serde.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
chrono.workspace = true
rand.workspace = true
rand_chacha.workspace = true
pin-project-lite.workspace = true
bytes.workspace = true
parking_lot.workspace = true
const_format.workspace = true
num_enum.workspace = true
socket2.workspace = true

tokio-rustls.workspace = true
webpki-roots.workspace = true

crypto.workspace = true
sys-process.workspace = true
net-packet.workspace = true
cc-server.workspace = true

if-addrs = "0.15.0"
#tun = {version = "0.8.6", features = ["async"]}
tun = {git = "https://github.com/wicked-code/rust-tun", features = ["async"]}
futures-util = "0.3.32"
tokio-util = "0.7.18"
network-interface = "2.0.5"
rustc-hash = "2.1.1"
arc-swap = "1.9.0"

hickory-client = { version = "0.25", default-features = false }
hickory-server = { version = "0.25", default-features = false }
hickory-proto = { version = "0.25", default-features = false }
hickory-resolver = { version = "0.25", default-features = false }

[features]
aws_lc_rs = [
    "tokio-rustls/aws_lc_rs",
    "hickory-server/https-aws-lc-rs",
    "hickory-server/h3-aws-lc-rs",
    "hickory-proto/dnssec-aws-lc-rs",
    "hickory-resolver/quic-aws-lc-rs",
]
default = ["rustls_ring"]
rustls_ring = [
    "tokio-rustls/ring",
    "hickory-server/https-ring",
    "hickory-server/h3-ring",
    "hickory-proto/dnssec-ring",
    "hickory-resolver/quic-ring",
]
