// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/log.dart';
import 'api/service.dart';
import 'api/wrappers.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1648889514;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_covert_connect',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiServiceRouterServiceAddServer({
    required RouterService that,
    required ServerConfig config,
  });

  Future<bool> crateApiServiceRouterServiceCheckDomain({
    required String domain,
  });

  Future<void> crateApiServiceRouterServiceDeleteServer({
    required RouterService that,
    required String host,
  });

  Future<bool> crateApiServiceRouterServiceGetAutostart();

  Future<RouterConfig> crateApiServiceRouterServiceGetConfig({
    required RouterService that,
  });

  Future<List<String>> crateApiServiceRouterServiceGetDirectApps({
    required RouterService that,
  });

  Future<List<String>> crateApiServiceRouterServiceGetDirectDomains({
    required RouterService that,
  });

  Future<List<LogLine>> crateApiServiceRouterServiceGetLog({
    BigInt? start,
    required BigInt limit,
  });

  Future<ProtocolConfig> crateApiServiceRouterServiceGetServerProtocol({
    required RouterService that,
    required String server,
    required String key,
  });

  Future<RouterState> crateApiServiceRouterServiceGetState({
    required RouterService that,
  });

  Future<RouterStatus> crateApiServiceRouterServiceGetStatus({
    required RouterService that,
  });

  Future<int> crateApiServiceRouterServiceGetTtfb({
    required RouterService that,
    required String server,
    required String domain,
  });

  Future<void> crateApiServiceRouterServiceLog({required String message});

  RouterService crateApiServiceRouterServiceNew();

  Future<BigInt> crateApiServiceRouterServiceRegisterLogger({
    required RouterService that,
    required FutureOr<void> Function(String) callback,
  });

  Future<void> crateApiServiceRouterServiceRemoveApp({
    required RouterService that,
    required String app,
  });

  Future<void> crateApiServiceRouterServiceRemoveDomain({
    required RouterService that,
    required String domain,
  });

  Future<void> crateApiServiceRouterServiceSetApp({
    required RouterService that,
    required String app,
    required String serverHost,
  });

  Future<void> crateApiServiceRouterServiceSetAutostart({
    required bool enabled,
  });

  Future<void> crateApiServiceRouterServiceSetDomain({
    required RouterService that,
    required String domain,
    required String serverHost,
  });

  Future<void> crateApiServiceRouterServiceSetServerEnabled({
    required RouterService that,
    required String host,
    required bool value,
  });

  Future<void> crateApiServiceRouterServiceSetState({
    required RouterService that,
    required RouterState state,
  });

  Future<void> crateApiServiceRouterServiceStart({
    required RouterService that,
    required RouterConfig cfg,
  });

  Future<void> crateApiServiceRouterServiceStop({required RouterService that});

  Future<void> crateApiServiceRouterServiceUnregisterLogger({
    required RouterService that,
    required BigInt id,
  });

  Future<void> crateApiServiceRouterServiceUpdateServer({
    required RouterService that,
    required String origHost,
    required ServerConfig newConfig,
  });

  Future<WriterNotifier> crateApiLogWriterNotifierNew();

  Future<BigInt> crateApiLogWriterNotifierRegisterLogger({
    required WriterNotifier that,
    required FutureOr<void> Function(String) callback,
  });

  Future<void> crateApiLogWriterNotifierUnregisterLogger({
    required WriterNotifier that,
    required BigInt id,
  });

  Future<List<LogLine>> crateApiLogGetTraceLog({
    BigInt? start,
    required BigInt limit,
  });

  Future<ArcWriterNotifier> crateApiLogInitTraceLog();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcWriterNotifier;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcWriterNotifier;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcWriterNotifierPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RouterService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RouterService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RouterServicePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WriterNotifier;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WriterNotifier;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WriterNotifierPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiServiceRouterServiceAddServer({
    required RouterService that,
    required ServerConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_box_autoadd_server_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceAddServerConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceAddServerConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_add_server",
        argNames: ["that", "config"],
      );

  @override
  Future<bool> crateApiServiceRouterServiceCheckDomain({
    required String domain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(domain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceCheckDomainConstMeta,
        argValues: [domain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceCheckDomainConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_check_domain",
        argNames: ["domain"],
      );

  @override
  Future<void> crateApiServiceRouterServiceDeleteServer({
    required RouterService that,
    required String host,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(host, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceDeleteServerConstMeta,
        argValues: [that, host],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceDeleteServerConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_delete_server",
        argNames: ["that", "host"],
      );

  @override
  Future<bool> crateApiServiceRouterServiceGetAutostart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetAutostartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetAutostartConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_autostart",
        argNames: [],
      );

  @override
  Future<RouterConfig> crateApiServiceRouterServiceGetConfig({
    required RouterService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_router_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetConfigConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_config",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiServiceRouterServiceGetDirectApps({
    required RouterService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetDirectAppsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetDirectAppsConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_direct_apps",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiServiceRouterServiceGetDirectDomains({
    required RouterService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetDirectDomainsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetDirectDomainsConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_direct_domains",
        argNames: ["that"],
      );

  @override
  Future<List<LogLine>> crateApiServiceRouterServiceGetLog({
    BigInt? start,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_64(start, serializer);
          sse_encode_usize(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_log_line,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetLogConstMeta,
        argValues: [start, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetLogConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_log",
        argNames: ["start", "limit"],
      );

  @override
  Future<ProtocolConfig> crateApiServiceRouterServiceGetServerProtocol({
    required RouterService that,
    required String server,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(server, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_protocol_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetServerProtocolConstMeta,
        argValues: [that, server, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetServerProtocolConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_server_protocol",
        argNames: ["that", "server", "key"],
      );

  @override
  Future<RouterState> crateApiServiceRouterServiceGetState({
    required RouterService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_router_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetStateConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_state",
        argNames: ["that"],
      );

  @override
  Future<RouterStatus> crateApiServiceRouterServiceGetStatus({
    required RouterService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_router_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetStatusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetStatusConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_status",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiServiceRouterServiceGetTtfb({
    required RouterService that,
    required String server,
    required String domain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(server, serializer);
          sse_encode_String(domain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceGetTtfbConstMeta,
        argValues: [that, server, domain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceGetTtfbConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_get_ttfb",
        argNames: ["that", "server", "domain"],
      );

  @override
  Future<void> crateApiServiceRouterServiceLog({required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiServiceRouterServiceLogConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceLogConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_log",
        argNames: ["message"],
      );

  @override
  RouterService crateApiServiceRouterServiceNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiServiceRouterServiceNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceNewConstMeta =>
      const TaskConstMeta(debugName: "RouterService_new", argNames: []);

  @override
  Future<BigInt> crateApiServiceRouterServiceRegisterLogger({
    required RouterService that,
    required FutureOr<void> Function(String) callback,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
            callback,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceRegisterLoggerConstMeta,
        argValues: [that, callback],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceRegisterLoggerConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_register_logger",
        argNames: ["that", "callback"],
      );

  @override
  Future<void> crateApiServiceRouterServiceRemoveApp({
    required RouterService that,
    required String app,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(app, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceRemoveAppConstMeta,
        argValues: [that, app],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceRemoveAppConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_remove_app",
        argNames: ["that", "app"],
      );

  @override
  Future<void> crateApiServiceRouterServiceRemoveDomain({
    required RouterService that,
    required String domain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(domain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceRemoveDomainConstMeta,
        argValues: [that, domain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceRemoveDomainConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_remove_domain",
        argNames: ["that", "domain"],
      );

  @override
  Future<void> crateApiServiceRouterServiceSetApp({
    required RouterService that,
    required String app,
    required String serverHost,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(app, serializer);
          sse_encode_String(serverHost, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceSetAppConstMeta,
        argValues: [that, app, serverHost],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceSetAppConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_set_app",
        argNames: ["that", "app", "serverHost"],
      );

  @override
  Future<void> crateApiServiceRouterServiceSetAutostart({
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceSetAutostartConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceSetAutostartConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_set_autostart",
        argNames: ["enabled"],
      );

  @override
  Future<void> crateApiServiceRouterServiceSetDomain({
    required RouterService that,
    required String domain,
    required String serverHost,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(domain, serializer);
          sse_encode_String(serverHost, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceSetDomainConstMeta,
        argValues: [that, domain, serverHost],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceSetDomainConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_set_domain",
        argNames: ["that", "domain", "serverHost"],
      );

  @override
  Future<void> crateApiServiceRouterServiceSetServerEnabled({
    required RouterService that,
    required String host,
    required bool value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(host, serializer);
          sse_encode_bool(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceSetServerEnabledConstMeta,
        argValues: [that, host, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceSetServerEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_set_server_enabled",
        argNames: ["that", "host", "value"],
      );

  @override
  Future<void> crateApiServiceRouterServiceSetState({
    required RouterService that,
    required RouterState state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_router_state(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceSetStateConstMeta,
        argValues: [that, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceSetStateConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_set_state",
        argNames: ["that", "state"],
      );

  @override
  Future<void> crateApiServiceRouterServiceStart({
    required RouterService that,
    required RouterConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_box_autoadd_router_config(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceStartConstMeta,
        argValues: [that, cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceStartConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_start",
        argNames: ["that", "cfg"],
      );

  @override
  Future<void> crateApiServiceRouterServiceStop({required RouterService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceStopConstMeta =>
      const TaskConstMeta(debugName: "RouterService_stop", argNames: ["that"]);

  @override
  Future<void> crateApiServiceRouterServiceUnregisterLogger({
    required RouterService that,
    required BigInt id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceUnregisterLoggerConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceUnregisterLoggerConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_unregister_logger",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateApiServiceRouterServiceUpdateServer({
    required RouterService that,
    required String origHost,
    required ServerConfig newConfig,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
            that,
            serializer,
          );
          sse_encode_String(origHost, serializer);
          sse_encode_box_autoadd_server_config(newConfig, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiServiceRouterServiceUpdateServerConstMeta,
        argValues: [that, origHost, newConfig],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServiceRouterServiceUpdateServerConstMeta =>
      const TaskConstMeta(
        debugName: "RouterService_update_server",
        argNames: ["that", "origHost", "newConfig"],
      );

  @override
  Future<WriterNotifier> crateApiLogWriterNotifierNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLogWriterNotifierNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogWriterNotifierNewConstMeta =>
      const TaskConstMeta(debugName: "WriterNotifier_new", argNames: []);

  @override
  Future<BigInt> crateApiLogWriterNotifierRegisterLogger({
    required WriterNotifier that,
    required FutureOr<void> Function(String) callback,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
            that,
            serializer,
          );
          sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
            callback,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLogWriterNotifierRegisterLoggerConstMeta,
        argValues: [that, callback],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogWriterNotifierRegisterLoggerConstMeta =>
      const TaskConstMeta(
        debugName: "WriterNotifier_register_logger",
        argNames: ["that", "callback"],
      );

  @override
  Future<void> crateApiLogWriterNotifierUnregisterLogger({
    required WriterNotifier that,
    required BigInt id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLogWriterNotifierUnregisterLoggerConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogWriterNotifierUnregisterLoggerConstMeta =>
      const TaskConstMeta(
        debugName: "WriterNotifier_unregister_logger",
        argNames: ["that", "id"],
      );

  @override
  Future<List<LogLine>> crateApiLogGetTraceLog({
    BigInt? start,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_64(start, serializer);
          sse_encode_usize(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_log_line,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLogGetTraceLogConstMeta,
        argValues: [start, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogGetTraceLogConstMeta => const TaskConstMeta(
    debugName: "get_trace_log",
    argNames: ["start", "limit"],
  );

  @override
  Future<ArcWriterNotifier> crateApiLogInitTraceLog() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLogInitTraceLogConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogInitTraceLogConstMeta =>
      const TaskConstMeta(debugName: "init_trace_log", argNames: []);

  Future<void> Function(int, dynamic)
  encode_DartFn_Inputs_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String) raw,
  ) {
    return (callId, rawArg0) async {
      final arg0 = dco_decode_String(rawArg0);

      Box<void>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_unit(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
        callId: callId,
        ptr: output.ptr,
        rustVecLen: output.rustVecLen,
        dataLen: output.dataLen,
      );
    };
  }

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcWriterNotifier => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcWriterNotifier => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RouterService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RouterService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WriterNotifier => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WriterNotifier => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ArcWriterNotifier
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcWriterNotifierImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RouterService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RouterServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WriterNotifier
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WriterNotifierImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RouterService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RouterServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WriterNotifier
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WriterNotifierImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FutureOr<void> Function(String)
  dco_decode_DartFn_Inputs_String_Output_unit_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  Object dco_decode_DartOpaque(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return decodeDartOpaque(raw, generalizedFrbRustBinding);
  }

  @protected
  ArcWriterNotifier
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcWriterNotifierImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RouterService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RouterServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WriterNotifier
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WriterNotifierImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RouterConfig dco_decode_box_autoadd_router_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_router_config(raw);
  }

  @protected
  ServerConfig dco_decode_box_autoadd_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_server_config(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CipherType dco_decode_cipher_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CipherType.values[raw as int];
  }

  @protected
  DataPadding dco_decode_data_padding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DataPadding(
      max: dco_decode_u_16(arr[0]),
      rate: dco_decode_u_8(arr[1]),
    );
  }

  @protected
  HeaderPadding dco_decode_header_padding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HeaderPadding(
      start: dco_decode_u_16(arr[0]),
      end: dco_decode_u_16(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Kdf dco_decode_kdf(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Kdf.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LogLine> dco_decode_list_log_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_log_line).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ServerConfig> dco_decode_list_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_server_config).toList();
  }

  @protected
  List<ServerInfo> dco_decode_list_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_server_info).toList();
  }

  @protected
  LogLine dco_decode_log_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LogLine(
      line: dco_decode_String(arr[0]),
      position: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  ProtocolConfig dco_decode_protocol_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ProtocolConfig(
      key: dco_decode_String(arr[0]),
      kdf: dco_decode_kdf(arr[1]),
      cipher: dco_decode_cipher_type(arr[2]),
      maxConnectDelay: dco_decode_u_16(arr[3]),
      headerPadding: dco_decode_header_padding(arr[4]),
      dataPadding: dco_decode_data_padding(arr[5]),
      encryptionLimit: dco_decode_usize(arr[6]),
    );
  }

  @protected
  RouterConfig dco_decode_router_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RouterConfig(
      state: dco_decode_router_state(arr[0]),
      directDomains: dco_decode_list_String(arr[1]),
      directApps: dco_decode_list_String(arr[2]),
      servers: dco_decode_list_server_config(arr[3]),
    );
  }

  @protected
  RouterState dco_decode_router_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RouterState.values[raw as int];
  }

  @protected
  RouterStatus dco_decode_router_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RouterStatus(
      initialized: dco_decode_bool(arr[0]),
      servers: dco_decode_list_server_info(arr[1]),
    );
  }

  @protected
  ServerConfig dco_decode_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ServerConfig(
      caption: dco_decode_opt_String(arr[0]),
      host: dco_decode_String(arr[1]),
      weight: dco_decode_opt_box_autoadd_u_8(arr[2]),
      domains: dco_decode_opt_list_String(arr[3]),
      apps: dco_decode_opt_list_String(arr[4]),
      enabled: dco_decode_bool(arr[5]),
      protocol: dco_decode_protocol_config(arr[6]),
    );
  }

  @protected
  ServerInfo dco_decode_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ServerInfo(
      state: dco_decode_server_state(arr[0]),
      config: dco_decode_server_config(arr[1]),
      ip: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
    );
  }

  @protected
  ServerState dco_decode_server_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ServerState(
      rxTotal: dco_decode_u_64(arr[0]),
      txTotal: dco_decode_u_64(arr[1]),
      errCount: dco_decode_u_64(arr[2]),
      succesCount: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ArcWriterNotifier
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcWriterNotifierImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RouterService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RouterServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WriterNotifier
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WriterNotifierImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RouterService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RouterServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WriterNotifier
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WriterNotifierImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_isize(deserializer);
    return decodeDartOpaque(inner, generalizedFrbRustBinding);
  }

  @protected
  ArcWriterNotifier
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcWriterNotifierImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RouterService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RouterServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WriterNotifier
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WriterNotifierImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RouterConfig sse_decode_box_autoadd_router_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_router_config(deserializer));
  }

  @protected
  ServerConfig sse_decode_box_autoadd_server_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_server_config(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  CipherType sse_decode_cipher_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CipherType.values[inner];
  }

  @protected
  DataPadding sse_decode_data_padding(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_max = sse_decode_u_16(deserializer);
    var var_rate = sse_decode_u_8(deserializer);
    return DataPadding(max: var_max, rate: var_rate);
  }

  @protected
  HeaderPadding sse_decode_header_padding(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_u_16(deserializer);
    var var_end = sse_decode_u_16(deserializer);
    return HeaderPadding(start: var_start, end: var_end);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Kdf sse_decode_kdf(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Kdf.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LogLine> sse_decode_list_log_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LogLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_log_line(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ServerConfig> sse_decode_list_server_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServerConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_server_config(deserializer));
    }
    return ans_;
  }

  @protected
  List<ServerInfo> sse_decode_list_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_server_info(deserializer));
    }
    return ans_;
  }

  @protected
  LogLine sse_decode_log_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_line = sse_decode_String(deserializer);
    var var_position = sse_decode_u_64(deserializer);
    return LogLine(line: var_line, position: var_position);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProtocolConfig sse_decode_protocol_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_kdf = sse_decode_kdf(deserializer);
    var var_cipher = sse_decode_cipher_type(deserializer);
    var var_maxConnectDelay = sse_decode_u_16(deserializer);
    var var_headerPadding = sse_decode_header_padding(deserializer);
    var var_dataPadding = sse_decode_data_padding(deserializer);
    var var_encryptionLimit = sse_decode_usize(deserializer);
    return ProtocolConfig(
      key: var_key,
      kdf: var_kdf,
      cipher: var_cipher,
      maxConnectDelay: var_maxConnectDelay,
      headerPadding: var_headerPadding,
      dataPadding: var_dataPadding,
      encryptionLimit: var_encryptionLimit,
    );
  }

  @protected
  RouterConfig sse_decode_router_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_router_state(deserializer);
    var var_directDomains = sse_decode_list_String(deserializer);
    var var_directApps = sse_decode_list_String(deserializer);
    var var_servers = sse_decode_list_server_config(deserializer);
    return RouterConfig(
      state: var_state,
      directDomains: var_directDomains,
      directApps: var_directApps,
      servers: var_servers,
    );
  }

  @protected
  RouterState sse_decode_router_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RouterState.values[inner];
  }

  @protected
  RouterStatus sse_decode_router_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_initialized = sse_decode_bool(deserializer);
    var var_servers = sse_decode_list_server_info(deserializer);
    return RouterStatus(initialized: var_initialized, servers: var_servers);
  }

  @protected
  ServerConfig sse_decode_server_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_caption = sse_decode_opt_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_weight = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_domains = sse_decode_opt_list_String(deserializer);
    var var_apps = sse_decode_opt_list_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    var var_protocol = sse_decode_protocol_config(deserializer);
    return ServerConfig(
      caption: var_caption,
      host: var_host,
      weight: var_weight,
      domains: var_domains,
      apps: var_apps,
      enabled: var_enabled,
      protocol: var_protocol,
    );
  }

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_server_state(deserializer);
    var var_config = sse_decode_server_config(deserializer);
    var var_ip = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    return ServerInfo(
      state: var_state,
      config: var_config,
      ip: var_ip,
      port: var_port,
    );
  }

  @protected
  ServerState sse_decode_server_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rxTotal = sse_decode_u_64(deserializer);
    var var_txTotal = sse_decode_u_64(deserializer);
    var var_errCount = sse_decode_u_64(deserializer);
    var var_succesCount = sse_decode_u_64(deserializer);
    return ServerState(
      rxTotal: var_rxTotal,
      txTotal: var_txTotal,
      errCount: var_errCount,
      succesCount: var_succesCount,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier(
    ArcWriterNotifier self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcWriterNotifierImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    RouterService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RouterServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    WriterNotifier self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WriterNotifierImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    RouterService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RouterServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    WriterNotifier self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WriterNotifierImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
      encode_DartFn_Inputs_String_Output_unit_AnyhowException(self),
      serializer,
    );
  }

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(
      PlatformPointerUtil.ptrToPlatformInt64(
        encodeDartOpaque(
          self,
          portManager.dartHandlerPort,
          generalizedFrbRustBinding,
        ),
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcWriterNotifier(
    ArcWriterNotifier self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcWriterNotifierImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRouterService(
    RouterService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RouterServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWriterNotifier(
    WriterNotifier self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WriterNotifierImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_router_config(
    RouterConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_router_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_server_config(
    ServerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_cipher_type(CipherType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_data_padding(DataPadding self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.max, serializer);
    sse_encode_u_8(self.rate, serializer);
  }

  @protected
  void sse_encode_header_padding(HeaderPadding self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.start, serializer);
    sse_encode_u_16(self.end, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_kdf(Kdf self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_log_line(List<LogLine> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_log_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_server_config(
    List<ServerConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_server_config(item, serializer);
    }
  }

  @protected
  void sse_encode_list_server_info(
    List<ServerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_server_info(item, serializer);
    }
  }

  @protected
  void sse_encode_log_line(LogLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.line, serializer);
    sse_encode_u_64(self.position, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_protocol_config(
    ProtocolConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_kdf(self.kdf, serializer);
    sse_encode_cipher_type(self.cipher, serializer);
    sse_encode_u_16(self.maxConnectDelay, serializer);
    sse_encode_header_padding(self.headerPadding, serializer);
    sse_encode_data_padding(self.dataPadding, serializer);
    sse_encode_usize(self.encryptionLimit, serializer);
  }

  @protected
  void sse_encode_router_config(RouterConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_router_state(self.state, serializer);
    sse_encode_list_String(self.directDomains, serializer);
    sse_encode_list_String(self.directApps, serializer);
    sse_encode_list_server_config(self.servers, serializer);
  }

  @protected
  void sse_encode_router_state(RouterState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_router_status(RouterStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.initialized, serializer);
    sse_encode_list_server_info(self.servers, serializer);
  }

  @protected
  void sse_encode_server_config(ServerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.caption, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_opt_box_autoadd_u_8(self.weight, serializer);
    sse_encode_opt_list_String(self.domains, serializer);
    sse_encode_opt_list_String(self.apps, serializer);
    sse_encode_bool(self.enabled, serializer);
    sse_encode_protocol_config(self.protocol, serializer);
  }

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_state(self.state, serializer);
    sse_encode_server_config(self.config, serializer);
    sse_encode_String(self.ip, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_server_state(ServerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.rxTotal, serializer);
    sse_encode_u_64(self.txTotal, serializer);
    sse_encode_u_64(self.errCount, serializer);
    sse_encode_u_64(self.succesCount, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ArcWriterNotifierImpl extends RustOpaque implements ArcWriterNotifier {
  // Not to be used by end users
  ArcWriterNotifierImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcWriterNotifierImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcWriterNotifier,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcWriterNotifier,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcWriterNotifierPtr,
  );
}

@sealed
class RouterServiceImpl extends RustOpaque implements RouterService {
  // Not to be used by end users
  RouterServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RouterServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RouterService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RouterService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RouterServicePtr,
  );

  Future<void> addServer({required ServerConfig config}) => RustLib.instance.api
      .crateApiServiceRouterServiceAddServer(that: this, config: config);

  Future<void> deleteServer({required String host}) => RustLib.instance.api
      .crateApiServiceRouterServiceDeleteServer(that: this, host: host);

  Future<RouterConfig> getConfig() =>
      RustLib.instance.api.crateApiServiceRouterServiceGetConfig(that: this);

  Future<List<String>> getDirectApps() => RustLib.instance.api
      .crateApiServiceRouterServiceGetDirectApps(that: this);

  Future<List<String>> getDirectDomains() => RustLib.instance.api
      .crateApiServiceRouterServiceGetDirectDomains(that: this);

  Future<ProtocolConfig> getServerProtocol({
    required String server,
    required String key,
  }) => RustLib.instance.api.crateApiServiceRouterServiceGetServerProtocol(
    that: this,
    server: server,
    key: key,
  );

  Future<RouterState> getState() =>
      RustLib.instance.api.crateApiServiceRouterServiceGetState(that: this);

  Future<RouterStatus> getStatus() =>
      RustLib.instance.api.crateApiServiceRouterServiceGetStatus(that: this);

  Future<int> getTtfb({required String server, required String domain}) =>
      RustLib.instance.api.crateApiServiceRouterServiceGetTtfb(
        that: this,
        server: server,
        domain: domain,
      );

  Future<BigInt> registerLogger({
    required FutureOr<void> Function(String) callback,
  }) => RustLib.instance.api.crateApiServiceRouterServiceRegisterLogger(
    that: this,
    callback: callback,
  );

  Future<void> removeApp({required String app}) => RustLib.instance.api
      .crateApiServiceRouterServiceRemoveApp(that: this, app: app);

  Future<void> removeDomain({required String domain}) => RustLib.instance.api
      .crateApiServiceRouterServiceRemoveDomain(that: this, domain: domain);

  Future<void> setApp({required String app, required String serverHost}) =>
      RustLib.instance.api.crateApiServiceRouterServiceSetApp(
        that: this,
        app: app,
        serverHost: serverHost,
      );

  Future<void> setDomain({
    required String domain,
    required String serverHost,
  }) => RustLib.instance.api.crateApiServiceRouterServiceSetDomain(
    that: this,
    domain: domain,
    serverHost: serverHost,
  );

  Future<void> setServerEnabled({required String host, required bool value}) =>
      RustLib.instance.api.crateApiServiceRouterServiceSetServerEnabled(
        that: this,
        host: host,
        value: value,
      );

  Future<void> setState({required RouterState state}) => RustLib.instance.api
      .crateApiServiceRouterServiceSetState(that: this, state: state);

  Future<void> start({required RouterConfig cfg}) => RustLib.instance.api
      .crateApiServiceRouterServiceStart(that: this, cfg: cfg);

  Future<void> stop() =>
      RustLib.instance.api.crateApiServiceRouterServiceStop(that: this);

  Future<void> unregisterLogger({required BigInt id}) => RustLib.instance.api
      .crateApiServiceRouterServiceUnregisterLogger(that: this, id: id);

  Future<void> updateServer({
    required String origHost,
    required ServerConfig newConfig,
  }) => RustLib.instance.api.crateApiServiceRouterServiceUpdateServer(
    that: this,
    origHost: origHost,
    newConfig: newConfig,
  );
}

@sealed
class WriterNotifierImpl extends RustOpaque implements WriterNotifier {
  // Not to be used by end users
  WriterNotifierImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WriterNotifierImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WriterNotifier,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WriterNotifier,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WriterNotifierPtr,
  );

  Future<BigInt> registerLogger({
    required FutureOr<void> Function(String) callback,
  }) => RustLib.instance.api.crateApiLogWriterNotifierRegisterLogger(
    that: this,
    callback: callback,
  );

  Future<void> unregisterLogger({required BigInt id}) => RustLib.instance.api
      .crateApiLogWriterNotifierUnregisterLogger(that: this, id: id);
}
