// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `move_reader_position`, `next_line`, `read_to_buffer`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Error`, `RevLines`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `source`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `current_position`, `new`, `with_capacity`

class RevLine {
  final String line;
  final BigInt position;

  const RevLine({required this.line, required this.position});

  @override
  int get hashCode => line.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RevLine &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          position == other.position;
}
