// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'log.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wrappers.dart';

// These functions are ignored because they are not marked as `pub`: `get_client`, `get_writer_notifier`, `init_autostart`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientService>>
abstract class ClientService implements RustOpaqueInterface {
  Future<void> addServer({required ServerConfig config});

  static Future<bool> checkDomain({required String domain}) => RustLib
      .instance
      .api
      .crateApiServiceClientServiceCheckDomain(domain: domain);

  Future<void> deleteServer({required String host});

  static Future<bool> getAutostart() =>
      RustLib.instance.api.crateApiServiceClientServiceGetAutostart();

  Future<ClientConfig> getConfig();

  Future<List<String>> getDirectApps();

  Future<List<String>> getDirectDomains();

  static Future<List<LogLine>> getLog({BigInt? start, required BigInt limit}) =>
      RustLib.instance.api.crateApiServiceClientServiceGetLog(
        start: start,
        limit: limit,
      );

  Future<ProtocolConfig> getServerProtocol({
    required String server,
    required String key,
  });

  Future<ClientState> getState();

  Future<ClientStatus> getStatus();

  Future<int> getTtfb({required String server, required String domain});

  static Future<void> log({required String message}) =>
      RustLib.instance.api.crateApiServiceClientServiceLog(message: message);

  factory ClientService() =>
      RustLib.instance.api.crateApiServiceClientServiceNew();

  Future<BigInt> registerLogger({
    required FutureOr<void> Function(String) callback,
  });

  Future<void> removeApp({required String app});

  Future<void> removeDomain({required String domain});

  Future<void> setApp({required String app, required String serverHost});

  static Future<void> setAutostart({required bool enabled}) => RustLib
      .instance
      .api
      .crateApiServiceClientServiceSetAutostart(enabled: enabled);

  Future<void> setDomain({required String domain, required String serverHost});

  Future<void> setServerEnabled({required String host, required bool value});

  Future<void> setState({required ClientState state});

  Future<void> start({required ClientConfig cfg});

  Future<void> stop();

  Future<void> unregisterLogger({required BigInt id});

  Future<void> updateServer({
    required String origHost,
    required ServerConfig newConfig,
  });
}

class ClientConfig {
  final ClientState state;
  final List<String> directDomains;
  final List<String> directApps;
  final List<ServerConfig> servers;

  const ClientConfig({
    required this.state,
    required this.directDomains,
    required this.directApps,
    required this.servers,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      directDomains.hashCode ^
      directApps.hashCode ^
      servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientConfig &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          directDomains == other.directDomains &&
          directApps == other.directApps &&
          servers == other.servers;
}

enum ClientState { smart, all, off }

class ClientStatus {
  final bool initialized;
  final bool working;
  final List<ServerInfo> servers;

  const ClientStatus({
    required this.initialized,
    required this.working,
    required this.servers,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^ working.hashCode ^ servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientStatus &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          working == other.working &&
          servers == other.servers;
}

class ServerInfo {
  final ServerState state;
  final ServerConfig config;
  final String? ip;
  final int? port;

  const ServerInfo({
    required this.state,
    required this.config,
    this.ip,
    this.port,
  });

  @override
  int get hashCode =>
      state.hashCode ^ config.hashCode ^ ip.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          config == other.config &&
          ip == other.ip &&
          port == other.port;
}

class ServerState {
  final BigInt rxTotal;
  final BigInt txTotal;
  final BigInt errCount;
  final BigInt successCount;

  const ServerState({
    required this.rxTotal,
    required this.txTotal,
    required this.errCount,
    required this.successCount,
  });

  @override
  int get hashCode =>
      rxTotal.hashCode ^
      txTotal.hashCode ^
      errCount.hashCode ^
      successCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerState &&
          runtimeType == other.runtimeType &&
          rxTotal == other.rxTotal &&
          txTotal == other.txTotal &&
          errCount == other.errCount &&
          successCount == other.successCount;
}
