// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'log.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wrappers.dart';

// These functions are ignored because they are not marked as `pub`: `get_router`, `get_writer_notifier`, `init_autostart`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RouterService>>
abstract class RouterService implements RustOpaqueInterface {
  Future<void> addServer({required ServerConfig config});

  static Future<bool> checkDomain({required String domain}) => RustLib
      .instance
      .api
      .crateApiServiceRouterServiceCheckDomain(domain: domain);

  Future<void> deleteServer({required String host});

  Future<List<String>> getApps();

  static Future<bool> getAutostart() =>
      RustLib.instance.api.crateApiServiceRouterServiceGetAutostart();

  Future<RouterConfig> getConfig();

  Future<List<String>> getDomains();

  static Future<List<LogLine>> getLog({BigInt? start, required BigInt limit}) =>
      RustLib.instance.api.crateApiServiceRouterServiceGetLog(
        start: start,
        limit: limit,
      );

  Future<RouterMode> getMode();

  Future<int> getProxyPort();

  Future<ProtocolConfig> getServerProtocol({
    required String server,
    required String key,
  });

  Future<RouterState> getState();

  Future<RouterStatus> getStatus();

  Future<int> getTtfb({required String server, required String domain});

  static Future<void> log({required String message}) =>
      RustLib.instance.api.crateApiServiceRouterServiceLog(message: message);

  factory RouterService() =>
      RustLib.instance.api.crateApiServiceRouterServiceNew();

  Future<BigInt> registerLogger({
    required FutureOr<void> Function(String) callback,
  });

  Future<void> removeApp({required String app});

  Future<void> removeDomain({required String domain});

  Future<void> setApp({required String app, required String serverHost});

  static Future<void> setAutostart({required bool enabled}) => RustLib
      .instance
      .api
      .crateApiServiceRouterServiceSetAutostart(enabled: enabled);

  Future<void> setDomain({required String domain, required String serverHost});

  Future<void> setMode({required RouterMode mode});

  Future<void> setProxyPort({required int port});

  Future<void> setServerEnabled({required String host, required bool value});

  Future<void> setState({required RouterState state});

  Future<void> start({required RouterConfig cfg});

  Future<void> stop();

  Future<void> unregisterLogger({required BigInt id});

  Future<void> updateServer({
    required String origHost,
    required ServerConfig newConfig,
  });
}

class RouterConfig {
  final RouterState state;
  final RouterMode mode;
  final int proxyPort;
  final List<String> domains;
  final List<String> apps;
  final List<ServerConfig> servers;

  const RouterConfig({
    required this.state,
    required this.mode,
    required this.proxyPort,
    required this.domains,
    required this.apps,
    required this.servers,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      mode.hashCode ^
      proxyPort.hashCode ^
      domains.hashCode ^
      apps.hashCode ^
      servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouterConfig &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          mode == other.mode &&
          proxyPort == other.proxyPort &&
          domains == other.domains &&
          apps == other.apps &&
          servers == other.servers;
}

enum RouterMode { proxy, tun }

enum RouterState { smart, all, off }

class RouterStatus {
  final bool initialized;
  final List<ServerInfo> servers;

  const RouterStatus({required this.initialized, required this.servers});

  @override
  int get hashCode => initialized.hashCode ^ servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouterStatus &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          servers == other.servers;
}

class ServerInfo {
  final ServerState state;
  final ServerConfig config;
  final String ip;
  final int port;

  const ServerInfo({
    required this.state,
    required this.config,
    required this.ip,
    required this.port,
  });

  @override
  int get hashCode =>
      state.hashCode ^ config.hashCode ^ ip.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          config == other.config &&
          ip == other.ip &&
          port == other.port;
}

class ServerState {
  final BigInt rxTotal;
  final BigInt txTotal;
  final BigInt errCount;
  final BigInt succesCount;

  const ServerState({
    required this.rxTotal,
    required this.txTotal,
    required this.errCount,
    required this.succesCount,
  });

  @override
  int get hashCode =>
      rxTotal.hashCode ^
      txTotal.hashCode ^
      errCount.hashCode ^
      succesCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerState &&
          runtimeType == other.runtimeType &&
          rxTotal == other.rxTotal &&
          txTotal == other.txTotal &&
          errCount == other.errCount &&
          succesCount == other.succesCount;
}
