// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `into`, `into`

enum CipherType { aes256Gcm, chaCha20Poly1305 }

class DataPadding {
  final int max;
  final int rate;

  const DataPadding({required this.max, required this.rate});

  @override
  int get hashCode => max.hashCode ^ rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataPadding &&
          runtimeType == other.runtimeType &&
          max == other.max &&
          rate == other.rate;
}

class HeaderPadding {
  final int start;
  final int end;

  const HeaderPadding({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeaderPadding &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

enum Kdf { argon2, blake3 }

class ProtocolConfig {
  final String key;
  final Kdf kdf;
  final CipherType cipher;
  final int maxConnectDelay;
  final HeaderPadding headerPadding;
  final DataPadding dataPadding;
  final BigInt encryptionLimit;

  const ProtocolConfig({
    required this.key,
    required this.kdf,
    required this.cipher,
    required this.maxConnectDelay,
    required this.headerPadding,
    required this.dataPadding,
    required this.encryptionLimit,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      kdf.hashCode ^
      cipher.hashCode ^
      maxConnectDelay.hashCode ^
      headerPadding.hashCode ^
      dataPadding.hashCode ^
      encryptionLimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolConfig &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          kdf == other.kdf &&
          cipher == other.cipher &&
          maxConnectDelay == other.maxConnectDelay &&
          headerPadding == other.headerPadding &&
          dataPadding == other.dataPadding &&
          encryptionLimit == other.encryptionLimit;
}

class ServerConfig {
  final String? caption;
  final String host;
  final int? weight;
  final List<String>? domains;
  final bool enabled;
  final ProtocolConfig protocol;

  const ServerConfig({
    this.caption,
    required this.host,
    this.weight,
    this.domains,
    required this.enabled,
    required this.protocol,
  });

  @override
  int get hashCode =>
      caption.hashCode ^
      host.hashCode ^
      weight.hashCode ^
      domains.hashCode ^
      enabled.hashCode ^
      protocol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerConfig &&
          runtimeType == other.runtimeType &&
          caption == other.caption &&
          host == other.host &&
          weight == other.weight &&
          domains == other.domains &&
          enabled == other.enabled &&
          protocol == other.protocol;
}
